services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  test:
    build: .
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=test
    depends_on:
      - api

volumes:
  mysql_data: 